"use strict";
console.log("================= belajar variable string =================");
const userName = "Max";
const userAddress = "New York";
const userAge = 30;
const description = "Hello, my name is " + userName + ". I live in " + userAddress + ". I am " + userAge + " years old.";
console.log(description);
console.log("================= belajar variable number =================");
const variableAngkaPertama = 10;
const variableAngkaKedua = 20;
const totalTambah = variableAngkaPertama + variableAngkaKedua;
const totalKurang = variableAngkaPertama - variableAngkaKedua;
const totalKali = variableAngkaPertama * variableAngkaKedua;
const totalBagi = variableAngkaPertama / variableAngkaKedua;
const totalModulus = variableAngkaPertama % variableAngkaKedua;
console.log("Hasil penjumlahan: " + variableAngkaPertama + variableAngkaKedua);
console.log("Hasil pengurangan: " + totalKurang);
console.log("Hasil perkalian: " + totalKali);
console.log("Hasil pembagian: " + totalBagi);
console.log("Hasil modulus: " + totalModulus);
console.log("================= belajar variable boolean =================");
const isUserArif = true;
const isLoginArif = false;
console.log("Apakah user adalah arif? " + isUserArif);
console.log("Apakah user yang login arif? " + isLoginArif);
console.log("Apakah user adalah arif dan yang login arif? " + (isUserArif && isLoginArif));
console.log("Apakah user adalah arif atau yang login arif? " + (isUserArif || isLoginArif));
console.log("Apakah user adalah arif dan yang login bukan arif? " + (isUserArif && !isLoginArif));
