"use strict";
console.log("================= belajar variable string =================");
const userName = "max";
const userAddress = "new york";
const userAge = 30;
const descriptsion = " Hello, my name is " + userName + " . I live in " + userAddress + " . I am " + userAge + " years old.";
console.log(descriptsion);
console.log("================= belajar variable number =================");
const variableangkaPertama = 10;
const variableangkaKedua = 20;
const totalTambah = variableangkaPertama + variableangkaKedua;
const totalKurang = variableangkaPertama - variableangkaKedua;
const totalKali = variableangkaPertama * variableangkaKedua;
const totalBagi = variableangkaPertama / variableangkaKedua;
const totalModulus = variableangkaPertama % variableangkaKedua;
console.log("hasil penjumlahan: " + totalTambah);
console.log("hasil pengurangan: " + totalKurang);
console.log("hasil perkalian: " + totalKali);
console.log("hasil pembagian: " + totalBagi);
console.log("hasil modulus: " + totalModulus);
console.log("================= belajar variable boolean =================");
const isUserArif = true;
const isLoginArif = false;
console.log("Apakah user adalah arif? " + isUserArif);
console.log("Apakah user yang login arif? " + isLoginArif);
console.log("Apakah user adalah arif dan yang login arif? " + (isUserArif && isLoginArif));
console.log("Apakah user adalah arif atau yang login arif? " + (isUserArif || isLoginArif));
console.log("Apakah user adalah arif dan yang login bukan arif? " + (isUserArif && !isLoginArif));
